"use client";

import { useMemo, useReducer, useState } from "react";
import Link from "next/link";
import { trendCandidates as initialCandidates, type TrendCandidate, type TrendStatus } from "@/data/trends";

type State = Record<string, TrendStatus>;
type Action =
  | { type: "approve"; id: string }
  | { type: "reject"; id: string }
  | { type: "revert"; id: string };

function statusReducer(state: State, action: Action): State {
  switch (action.type) {
    case "approve":
      return { ...state, [action.id]: "approved" };
    case "reject":
      return { ...state, [action.id]: "rejected" };
    case "revert":
      return { ...state, [action.id]: "pending" };
    default:
      return state;
  }
}

const FILTERS: { key: "all" | TrendStatus; label: string }[] = [
  { key: "all", label: "All" },
  { key: "pending", label: "Pending" },
  { key: "approved", label: "Approved" },
  { key: "rejected", label: "Rejected" },
];

const STATUS_STYLE: Record<TrendStatus, string> = {
  pending: "bg-amber-50 text-amber-800 ring-1 ring-inset ring-amber-200",
  approved: "bg-emerald-50 text-emerald-800 ring-1 ring-inset ring-emerald-200",
  rejected: "bg-rose-50 text-rose-800 ring-1 ring-inset ring-rose-200",
};

export default function TrendDashboardPage() {
  const initialState = useMemo<State>(
    () => Object.fromEntries(initialCandidates.map((c) => [c.id, c.status])),
    [],
  );
  const [statuses, dispatch] = useReducer(statusReducer, initialState);
  const [filter, setFilter] = useState<"all" | TrendStatus>("all");

  const candidates: TrendCandidate[] = initialCandidates.map((c) => ({
    ...c,
    status: statuses[c.id],
  }));

  const counts = {
    all: candidates.length,
    pending: candidates.filter((c) => c.status === "pending").length,
    approved: candidates.filter((c) => c.status === "approved").length,
    rejected: candidates.filter((c) => c.status === "rejected").length,
  };

  const visible =
    filter === "all" ? candidates : candidates.filter((c) => c.status === filter);

  return (
    <div className="flex flex-1 flex-col bg-slate-50 font-sans text-slate-900">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-6 py-5">
          <div>
            <p className="font-mono text-[10px] uppercase tracking-widest text-slate-400">
              Staff only
            </p>
            <h1 className="mt-1 text-xl font-semibold text-slate-900">
              Trend review
            </h1>
            <p className="mt-1 max-w-lg text-sm text-slate-500">
              Weekly trend-intake candidates, drafted and image-regenerated by
              the AI pipeline. Nothing here reaches the catalog until a
              stylist approves it.
            </p>
          </div>
          <Link
            href="/"
            className="rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-600 transition-colors hover:border-slate-400 hover:text-slate-900"
          >
            ← Back to site
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 py-8">
        <div className="flex flex-wrap items-center gap-2">
          {FILTERS.map((f) => (
            <button
              key={f.key}
              onClick={() => setFilter(f.key)}
              className={`rounded-full px-3.5 py-1.5 text-sm font-medium transition-colors ${
                filter === f.key
                  ? "bg-slate-900 text-white"
                  : "bg-white text-slate-600 ring-1 ring-inset ring-slate-200 hover:bg-slate-100"
              }`}
            >
              {f.label}
              <span className="ml-1.5 font-mono text-xs opacity-70">
                {counts[f.key]}
              </span>
            </button>
          ))}
        </div>

        {visible.length === 0 ? (
          <p className="mt-16 text-center text-sm text-slate-400">
            Nothing in this view.
          </p>
        ) : (
          <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {visible.map((c) => (
              <article
                key={c.id}
                className="flex flex-col overflow-hidden rounded-lg border border-slate-200 bg-white"
              >
                <div
                  className="h-36 w-full"
                  style={{ background: c.gradient }}
                  aria-hidden
                />
                <div className="flex flex-1 flex-col gap-3 p-4">
                  <div className="flex items-start justify-between gap-2">
                    <h2 className="text-sm font-semibold leading-snug text-slate-900">
                      {c.title}
                    </h2>
                    <span
                      className={`shrink-0 rounded-full px-2 py-0.5 font-mono text-[10px] uppercase tracking-wide ${STATUS_STYLE[c.status]}`}
                    >
                      {c.status}
                    </span>
                  </div>

                  <span className="w-fit rounded border border-slate-200 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wide text-slate-500">
                    {c.garmentType}
                  </span>

                  <p className="text-xs leading-relaxed text-slate-600">
                    {c.signal}
                  </p>

                  <div className="mt-auto flex items-center justify-between font-mono text-[10px] text-slate-400">
                    <span>
                      {c.sourceCount} sources · {c.weeksRunning}w running
                    </span>
                    <span>{c.detectedAt}</span>
                  </div>

                  <div className="flex gap-2 pt-1">
                    {c.status === "pending" ? (
                      <>
                        <button
                          onClick={() => dispatch({ type: "approve", id: c.id })}
                          className="flex-1 rounded-md bg-emerald-600 py-2 text-xs font-medium text-white transition-opacity hover:opacity-90"
                        >
                          Approve
                        </button>
                        <button
                          onClick={() => dispatch({ type: "reject", id: c.id })}
                          className="flex-1 rounded-md bg-rose-600 py-2 text-xs font-medium text-white transition-opacity hover:opacity-90"
                        >
                          Reject
                        </button>
                      </>
                    ) : (
                      <button
                        onClick={() => dispatch({ type: "revert", id: c.id })}
                        className="flex-1 rounded-md border border-slate-300 py-2 text-xs font-medium text-slate-600 transition-colors hover:bg-slate-100"
                      >
                        Revert to pending
                      </button>
                    )}
                  </div>
                </div>
              </article>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
